<a href="https://colab.research.google.com/github/Leeladewa/bioinformatics_operation/blob/master/TensorflowTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
% tensorflow_version 1x

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `1x`. This will be interpreted as: `1.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [30]:
import tensorflow as tf
from tensorflow.python.framework import ops
print(tf.__version__)
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

1.15.2


In [ ]:
Y_hat = tf.constant(36, name='Y_hat')
y = tf.constant(39, name='y')
loss = tf.Variable((y-Y_hat)**2, name='loss')
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(loss))

9


In [ ]:
a = tf.constant(2)
b = tf.constant(10)
c = tf.multiply(a,b)
sess = tf.Session()
print(sess.run(c))

20


In [ ]:
x = tf.placeholder(tf.int64,shape=None, name='x')
print(sess.run(2*x, feed_dict={x:3}))
sess.close()

6


In [35]:
import numpy as np
print("successful")
def linear_function():
  x = np.random.randn(3,1)
  W = np.random.randn(4,3)
  b = np.random.randn(4,1)
  y = tf.add(tf.matmul(W,x),b)
  sess  = tf.Session()
  print(sess.run(y))
  sess.close()


linear_function()

successful
[[ 0.7586093 ]
 [-2.5291411 ]
 [ 1.44473517]
 [ 0.29075693]]


In [ ]:
def sigmoid(z):
  x = tf.placeholder(tf.float32, name= 'x')
  sigmoid = tf.sigmoid(x)
  sess = tf.Session()
  result = sess.run(sigmoid, feed_dict = {x:3})
  sess.close()
  return result
print("sigmoid(0) = "+str(sigmoid(0)))
print("sigmoid(12) = "+str(sigmoid(12)))


sigmoid(0) = 0.95257413
sigmoid(12) = 0.95257413


In [39]:
def cost(logits, labels):
  z = tf.placeholder(tf.float32,name = 'z')
  y = tf.placeholder(tf.float32, name = 'y')
  cost = tf.nn.sigmoid_cross_entropy_with_logits(logits=z, labels=y)
  sess = tf.Session()
  cost = sess.run(cost,feed_dict = {z:logits, y:labels})
  sess.close()
  return cost

logits = np.array([0.2,0.4,0.7,0.9])
cost = cost(logits, np.array([0,0,1,1]))
print("cost = "+str(cost))

cost = [0.79813886 0.91301525 0.40318605 0.34115386]


In [41]:
def one_hot_matrix(labels, c):
  C = tf.constant(c,name='c')
  one_hot = tf.one_hot(labels, depth=C, axis=1) 
  sess = tf.Session()
  one_hot = sess.run(one_hot)
  sess.close()
  return one_hot

labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, c=4) 
print('one_hot = \n'+str(one_hot)) 

one_hot = 
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [43]:
def ones(shape):
  ones = tf.ones(shape)
  sess = tf.Session()
  ones = sess.run(ones)
  sess.close()
  return ones
print("ones = \n "+str(ones([3])))  

ones = 
 [1. 1. 1.]


In [44]:
def create_placeholder(n_x, n_y):
  X = tf.placeholder(tf.float32,shape=[n_x, None])
  Y = tf.placeholder(tf.float32,shape=[n_y, None])
  return X, Y
X, Y = create_placeholder(12288, 6)
print("X = "+str(X))
print("Y = "+str(Y))  

X = Tensor("Placeholder:0", shape=(12288, ?), dtype=float32)
Y = Tensor("Placeholder_1:0", shape=(6, ?), dtype=float32)


In [50]:
def initialize_parameters():
  W1 = tf.get_variable("W1",[25,12288], initializer=tf.contrib.layers.xavier_initializer())
  b1 = tf.get_variable("b1",[25,1],initializer=tf.zeros_initializer())
  W2 = tf.get_variable("W2",[12,25], initializer=tf.contrib.layers.xavier_initializer())
  b2 = tf.get_variable("b2",[12,1],initializer=tf.zeros_initializer())
  W3 = tf.get_variable("W3",[6,12], initializer=tf.contrib.layers.xavier_initializer())
  b3 = tf.get_variable("b3",[6,1],initializer=tf.zeros_initializer())
  parameters = {"W1":W1,
                "b1":b1,
                "W2":W2,
                "b2":b2,
                "W3":W3,
                "b3":b3}
  return parameters
tf.reset_default_graph()
with tf.Session() as sess:
  parameters = sess.run(initialize_parameters())
  print("W1 = " + str(parameters["W1"]))


FailedPreconditionError: ignored